/*
 * Overview
 * Fetch company/companies overview(s)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.roaring.example.overview.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MultiCompanyRequest
 */
public class MultiCompanyRequestTest {
    private final MultiCompanyRequest model = new MultiCompanyRequest();

    /**
     * Model tests for MultiCompanyRequest
     */
    @Test
    public void testMultiCompanyRequest() {
        // TODO: test MultiCompanyRequest
    }

    /**
     * Test the property 'companyIds'
     */
    @Test
    public void companyIdsTest() {
        // TODO: test companyIds
    }

    /**
     * Test the property 'requestKey'
     */
    @Test
    public void requestKeyTest() {
        // TODO: test requestKey
    }

}
