/*
 * Overview
 * Fetch company/companies overview(s)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.roaring.example.overview.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.roaring.example.overview.model.Overview;
import io.roaring.example.overview.model.SearchResultStatus;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OverviewsResult
 */
public class OverviewsResultTest {
    private final OverviewsResult model = new OverviewsResult();

    /**
     * Model tests for OverviewsResult
     */
    @Test
    public void testOverviewsResult() {
        // TODO: test OverviewsResult
    }

    /**
     * Test the property 'records'
     */
    @Test
    public void recordsTest() {
        // TODO: test records
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

}
