/*
 * Overview
 * Fetch company/companies overview(s)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.roaring.example.overview.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ResponseInfo
 */
public class ResponseInfoTest {
    private final ResponseInfo model = new ResponseInfo();

    /**
     * Model tests for ResponseInfo
     */
    @Test
    public void testResponseInfo() {
        // TODO: test ResponseInfo
    }

    /**
     * Test the property 'hitCount'
     */
    @Test
    public void hitCountTest() {
        // TODO: test hitCount
    }

    /**
     * Test the property 'noMatchIds'
     */
    @Test
    public void noMatchIdsTest() {
        // TODO: test noMatchIds
    }

    /**
     * Test the property 'requestCount'
     */
    @Test
    public void requestCountTest() {
        // TODO: test requestCount
    }

}
