/*
 * Overview
 * Fetch company/companies overview(s)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.roaring.example.companyinfo.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Overview
 */
public class OverviewTest {
    private final Overview model = new Overview();

    /**
     * Model tests for Overview
     */
    @Test
    public void testOverview() {
        // TODO: test Overview
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'changeDate'
     */
    @Test
    public void changeDateTest() {
        // TODO: test changeDate
    }

    /**
     * Test the property 'coAddress'
     */
    @Test
    public void coAddressTest() {
        // TODO: test coAddress
    }

    /**
     * Test the property 'commune'
     */
    @Test
    public void communeTest() {
        // TODO: test commune
    }

    /**
     * Test the property 'communeCode'
     */
    @Test
    public void communeCodeTest() {
        // TODO: test communeCode
    }

    /**
     * Test the property 'companyDeregistrationDate'
     */
    @Test
    public void companyDeregistrationDateTest() {
        // TODO: test companyDeregistrationDate
    }

    /**
     * Test the property 'companyHolder'
     */
    @Test
    public void companyHolderTest() {
        // TODO: test companyHolder
    }

    /**
     * Test the property 'companyId'
     */
    @Test
    public void companyIdTest() {
        // TODO: test companyId
    }

    /**
     * Test the property 'companyName'
     */
    @Test
    public void companyNameTest() {
        // TODO: test companyName
    }

    /**
     * Test the property 'companyRegistrationDate'
     */
    @Test
    public void companyRegistrationDateTest() {
        // TODO: test companyRegistrationDate
    }

    /**
     * Test the property 'county'
     */
    @Test
    public void countyTest() {
        // TODO: test county
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'employerContributionReg'
     */
    @Test
    public void employerContributionRegTest() {
        // TODO: test employerContributionReg
    }

    /**
     * Test the property 'faxNumber'
     */
    @Test
    public void faxNumberTest() {
        // TODO: test faxNumber
    }

    /**
     * Test the property 'industryCode'
     */
    @Test
    public void industryCodeTest() {
        // TODO: test industryCode
    }

    /**
     * Test the property 'industryText'
     */
    @Test
    public void industryTextTest() {
        // TODO: test industryText
    }

    /**
     * Test the property 'legalGroupCode'
     */
    @Test
    public void legalGroupCodeTest() {
        // TODO: test legalGroupCode
    }

    /**
     * Test the property 'legalGroupText'
     */
    @Test
    public void legalGroupTextTest() {
        // TODO: test legalGroupText
    }

    /**
     * Test the property 'numberCompanyUnits'
     */
    @Test
    public void numberCompanyUnitsTest() {
        // TODO: test numberCompanyUnits
    }

    /**
     * Test the property 'numberEmployeesInterval'
     */
    @Test
    public void numberEmployeesIntervalTest() {
        // TODO: test numberEmployeesInterval
    }

    /**
     * Test the property 'phoneNumber'
     */
    @Test
    public void phoneNumberTest() {
        // TODO: test phoneNumber
    }

    /**
     * Test the property 'preliminaryTaxReg'
     */
    @Test
    public void preliminaryTaxRegTest() {
        // TODO: test preliminaryTaxReg
    }

    /**
     * Test the property 'preliminaryTaxRegDate'
     */
    @Test
    public void preliminaryTaxRegDateTest() {
        // TODO: test preliminaryTaxRegDate
    }

    /**
     * Test the property 'severalCompanyName'
     */
    @Test
    public void severalCompanyNameTest() {
        // TODO: test severalCompanyName
    }

    /**
     * Test the property 'statusCode'
     */
    @Test
    public void statusCodeTest() {
        // TODO: test statusCode
    }

    /**
     * Test the property 'statusDateFrom'
     */
    @Test
    public void statusDateFromTest() {
        // TODO: test statusDateFrom
    }

    /**
     * Test the property 'statusTextDetailed'
     */
    @Test
    public void statusTextDetailedTest() {
        // TODO: test statusTextDetailed
    }

    /**
     * Test the property 'statusTextHigh'
     */
    @Test
    public void statusTextHighTest() {
        // TODO: test statusTextHigh
    }

    /**
     * Test the property 'topDirectorFunction'
     */
    @Test
    public void topDirectorFunctionTest() {
        // TODO: test topDirectorFunction
    }

    /**
     * Test the property 'topDirectorName'
     */
    @Test
    public void topDirectorNameTest() {
        // TODO: test topDirectorName
    }

    /**
     * Test the property 'town'
     */
    @Test
    public void townTest() {
        // TODO: test town
    }

    /**
     * Test the property 'vatReg'
     */
    @Test
    public void vatRegTest() {
        // TODO: test vatReg
    }

    /**
     * Test the property 'vatRegDate'
     */
    @Test
    public void vatRegDateTest() {
        // TODO: test vatRegDate
    }

    /**
     * Test the property 'visitAddress'
     */
    @Test
    public void visitAddressTest() {
        // TODO: test visitAddress
    }

    /**
     * Test the property 'visitCommune'
     */
    @Test
    public void visitCommuneTest() {
        // TODO: test visitCommune
    }

    /**
     * Test the property 'visitCounty'
     */
    @Test
    public void visitCountyTest() {
        // TODO: test visitCounty
    }

    /**
     * Test the property 'visitStreet'
     */
    @Test
    public void visitStreetTest() {
        // TODO: test visitStreet
    }

    /**
     * Test the property 'visitTown'
     */
    @Test
    public void visitTownTest() {
        // TODO: test visitTown
    }

    /**
     * Test the property 'visitZipCode'
     */
    @Test
    public void visitZipCodeTest() {
        // TODO: test visitZipCode
    }

    /**
     * Test the property 'webAddress'
     */
    @Test
    public void webAddressTest() {
        // TODO: test webAddress
    }

    /**
     * Test the property 'zipCode'
     */
    @Test
    public void zipCodeTest() {
        // TODO: test zipCode
    }

}
