/*
 * Overview
 * Fetch company/companies overview(s)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.roaring.example.companyinfo.api;

import io.roaring.example.companyinfo.invoker.ApiException;
import io.roaring.example.companyinfo.model.BadRequest;
import io.roaring.example.companyinfo.model.MultiCompaniesOverviewsResult;
import io.roaring.example.companyinfo.model.MultiCompanyRequest;
import io.roaring.example.companyinfo.model.OverviewsResult;
import io.roaring.example.companyinfo.model.ServerError;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Disabled
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    /**
     * Find overview by company id
     *
     * It supports date parameter to find overview up to date
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void companyIdGetTest() throws ApiException {
        String companyId = null;
        OverviewsResult response = api.companyIdGet(companyId);
        // TODO: test validations
    }

    /**
     * Find history overview by company id
     *
     * Changes of the company within specified date range. The range includes \&quot;from\&quot; and excludes \&quot;to\&quot;.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void historyCompanyIdGetTest() throws ApiException {
        String companyId = null;
        String fromDate = null;
        String toDate = null;
        OverviewsResult response = api.historyCompanyIdGet(companyId, fromDate, toDate);
        // TODO: test validations
    }

    /**
     * Find overviews by companies id-s
     *
     * It supports date parameter to find overviews up to date
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void rootPostTest() throws ApiException {
        MultiCompanyRequest multiCompanyRequest = null;
        MultiCompaniesOverviewsResult response = api.rootPost(multiCompanyRequest);
        // TODO: test validations
    }

}
