/*
 * Overview
 * Fetch company/companies overview(s)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.roaring.example.companyinfo.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.roaring.example.companyinfo.model.Overview;
import io.roaring.example.companyinfo.model.ResponseInfo;
import io.roaring.example.companyinfo.model.SearchResultStatus;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.roaring.example.companyinfo.invoker.JSON;

/**
 * Multiple companies overviews result
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-11T11:07:20.642217455+01:00[Europe/Stockholm]", comments = "Generator version: 7.12.0")
public class MultiCompaniesOverviewsResult {
  public static final String SERIALIZED_NAME_RECORDS = "records";
  @SerializedName(SERIALIZED_NAME_RECORDS)
  @javax.annotation.Nullable
  private List<Overview> records = new ArrayList<>();

  public static final String SERIALIZED_NAME_RESPONSE_INFO = "responseInfo";
  @SerializedName(SERIALIZED_NAME_RESPONSE_INFO)
  @javax.annotation.Nullable
  private ResponseInfo responseInfo;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private SearchResultStatus status;

  public MultiCompaniesOverviewsResult() {
  }

  public MultiCompaniesOverviewsResult records(@javax.annotation.Nullable List<Overview> records) {
    this.records = records;
    return this;
  }

  public MultiCompaniesOverviewsResult addRecordsItem(Overview recordsItem) {
    if (this.records == null) {
      this.records = new ArrayList<>();
    }
    this.records.add(recordsItem);
    return this;
  }

  /**
   * found overview(s)
   * @return records
   */
  @javax.annotation.Nullable
  public List<Overview> getRecords() {
    return records;
  }

  public void setRecords(@javax.annotation.Nullable List<Overview> records) {
    this.records = records;
  }


  public MultiCompaniesOverviewsResult responseInfo(@javax.annotation.Nullable ResponseInfo responseInfo) {
    this.responseInfo = responseInfo;
    return this;
  }

  /**
   * Get responseInfo
   * @return responseInfo
   */
  @javax.annotation.Nullable
  public ResponseInfo getResponseInfo() {
    return responseInfo;
  }

  public void setResponseInfo(@javax.annotation.Nullable ResponseInfo responseInfo) {
    this.responseInfo = responseInfo;
  }


  public MultiCompaniesOverviewsResult status(@javax.annotation.Nullable SearchResultStatus status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  public SearchResultStatus getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nullable SearchResultStatus status) {
    this.status = status;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MultiCompaniesOverviewsResult multiCompaniesOverviewsResult = (MultiCompaniesOverviewsResult) o;
    return Objects.equals(this.records, multiCompaniesOverviewsResult.records) &&
        Objects.equals(this.responseInfo, multiCompaniesOverviewsResult.responseInfo) &&
        Objects.equals(this.status, multiCompaniesOverviewsResult.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(records, responseInfo, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MultiCompaniesOverviewsResult {\n");
    sb.append("    records: ").append(toIndentedString(records)).append("\n");
    sb.append("    responseInfo: ").append(toIndentedString(responseInfo)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("records");
    openapiFields.add("responseInfo");
    openapiFields.add("status");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to MultiCompaniesOverviewsResult
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!MultiCompaniesOverviewsResult.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in MultiCompaniesOverviewsResult is not found in the empty JSON string", MultiCompaniesOverviewsResult.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!MultiCompaniesOverviewsResult.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `MultiCompaniesOverviewsResult` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("records") != null && !jsonObj.get("records").isJsonNull()) {
        JsonArray jsonArrayrecords = jsonObj.getAsJsonArray("records");
        if (jsonArrayrecords != null) {
          // ensure the json data is an array
          if (!jsonObj.get("records").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `records` to be an array in the JSON string but got `%s`", jsonObj.get("records").toString()));
          }

          // validate the optional field `records` (array)
          for (int i = 0; i < jsonArrayrecords.size(); i++) {
            Overview.validateJsonElement(jsonArrayrecords.get(i));
          };
        }
      }
      // validate the optional field `responseInfo`
      if (jsonObj.get("responseInfo") != null && !jsonObj.get("responseInfo").isJsonNull()) {
        ResponseInfo.validateJsonElement(jsonObj.get("responseInfo"));
      }
      // validate the optional field `status`
      if (jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) {
        SearchResultStatus.validateJsonElement(jsonObj.get("status"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MultiCompaniesOverviewsResult.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MultiCompaniesOverviewsResult' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MultiCompaniesOverviewsResult> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MultiCompaniesOverviewsResult.class));

       return (TypeAdapter<T>) new TypeAdapter<MultiCompaniesOverviewsResult>() {
           @Override
           public void write(JsonWriter out, MultiCompaniesOverviewsResult value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public MultiCompaniesOverviewsResult read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of MultiCompaniesOverviewsResult given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of MultiCompaniesOverviewsResult
   * @throws IOException if the JSON string is invalid with respect to MultiCompaniesOverviewsResult
   */
  public static MultiCompaniesOverviewsResult fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MultiCompaniesOverviewsResult.class);
  }

  /**
   * Convert an instance of MultiCompaniesOverviewsResult to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

