/*
 * Overview
 * Fetch company/companies overview(s)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.roaring.example.overview.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.roaring.example.overview.invoker.JSON;

/**
 * Multiple companies ids request
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-07T16:44:53.614776147+01:00[Europe/Stockholm]", comments = "Generator version: 7.12.0")
public class MultiCompanyRequest {
  public static final String SERIALIZED_NAME_COMPANY_IDS = "companyIds";
  @SerializedName(SERIALIZED_NAME_COMPANY_IDS)
  @javax.annotation.Nullable
  private List<String> companyIds = new ArrayList<>();

  public static final String SERIALIZED_NAME_REQUEST_KEY = "requestKey";
  @SerializedName(SERIALIZED_NAME_REQUEST_KEY)
  @javax.annotation.Nullable
  private String requestKey;

  public MultiCompanyRequest() {
  }

  public MultiCompanyRequest companyIds(@javax.annotation.Nullable List<String> companyIds) {
    this.companyIds = companyIds;
    return this;
  }

  public MultiCompanyRequest addCompanyIdsItem(String companyIdsItem) {
    if (this.companyIds == null) {
      this.companyIds = new ArrayList<>();
    }
    this.companyIds.add(companyIdsItem);
    return this;
  }

  /**
   * array of company id
   * @return companyIds
   */
  @javax.annotation.Nullable
  public List<String> getCompanyIds() {
    return companyIds;
  }

  public void setCompanyIds(@javax.annotation.Nullable List<String> companyIds) {
    this.companyIds = companyIds;
  }


  public MultiCompanyRequest requestKey(@javax.annotation.Nullable String requestKey) {
    this.requestKey = requestKey;
    return this;
  }

  /**
   * cache key for companies id-s in sandbox
   * @return requestKey
   */
  @javax.annotation.Nullable
  public String getRequestKey() {
    return requestKey;
  }

  public void setRequestKey(@javax.annotation.Nullable String requestKey) {
    this.requestKey = requestKey;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MultiCompanyRequest multiCompanyRequest = (MultiCompanyRequest) o;
    return Objects.equals(this.companyIds, multiCompanyRequest.companyIds) &&
        Objects.equals(this.requestKey, multiCompanyRequest.requestKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(companyIds, requestKey);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MultiCompanyRequest {\n");
    sb.append("    companyIds: ").append(toIndentedString(companyIds)).append("\n");
    sb.append("    requestKey: ").append(toIndentedString(requestKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("companyIds");
    openapiFields.add("requestKey");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to MultiCompanyRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!MultiCompanyRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in MultiCompanyRequest is not found in the empty JSON string", MultiCompanyRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!MultiCompanyRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `MultiCompanyRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the optional json data is an array if present
      if (jsonObj.get("companyIds") != null && !jsonObj.get("companyIds").isJsonNull() && !jsonObj.get("companyIds").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `companyIds` to be an array in the JSON string but got `%s`", jsonObj.get("companyIds").toString()));
      }
      if ((jsonObj.get("requestKey") != null && !jsonObj.get("requestKey").isJsonNull()) && !jsonObj.get("requestKey").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `requestKey` to be a primitive type in the JSON string but got `%s`", jsonObj.get("requestKey").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MultiCompanyRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MultiCompanyRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MultiCompanyRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MultiCompanyRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<MultiCompanyRequest>() {
           @Override
           public void write(JsonWriter out, MultiCompanyRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public MultiCompanyRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of MultiCompanyRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of MultiCompanyRequest
   * @throws IOException if the JSON string is invalid with respect to MultiCompanyRequest
   */
  public static MultiCompanyRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MultiCompanyRequest.class);
  }

  /**
   * Convert an instance of MultiCompanyRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

